In [1]:
import pandas as pd
df = pd.read_csv("../Dataset/HDI.csv")
print(df.shape)
df.head()

(195, 880)

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Human Development Index (1990),Human Development Index (1991),Human Development Index (1992),Human Development Index (1993),Human Development Index (1994),...,Material footprint per capita (tonnes) (2012),Material footprint per capita (tonnes) (2013),Material footprint per capita (tonnes) (2014),Material footprint per capita (tonnes) (2015),Material footprint per capita (tonnes) (2016),Material footprint per capita (tonnes) (2017),Material footprint per capita (tonnes) (2018),Material footprint per capita (tonnes) (2019),Material footprint per capita (tonnes) (2020),Material footprint per capita (tonnes) (2021)
0,AFG,Afghanistan,Low,SA,180.0,0.273,0.279,0.287,0.297,0.292,...,1.86,1.88,1.66,1.62,1.66,1.41,1.32,1.38,1.38,1.38
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,4.09,4.53,3.97,3.59,2.79,2.64,2.28,2.18,2.18,2.18
2,ALB,Albania,High,ECA,67.0,0.647,0.629,0.614,0.617,0.624,...,12.44,11.49,13.14,12.61,14.39,14.46,12.85,12.96,12.96,12.96
3,AND,Andorra,Very High,NaN,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Very High,AS,26.0,0.728,0.739,0.742,0.748,0.755,...,49.56,49.68,55.49,59.76,64.95,75.61,65.97,68.95,68.95,68.95

In [2]:
# అన్ని column పేర్లలో 2021 unna vaatini chudam
cols_2021 = [c for c in df.columns if '2021' in c]
print(cols_2021)

['HDI Rank (2021)', 'Human Development Index (2021)', 'Life Expectancy at Birth (2021)', 'Expected Years of Schooling (2021)', 'Mean Years of Schooling (2021)', 'Gross National Income Per Capita (2021)', 'GDI Group (2021)', 'Gender Development Index (2021)', 'HDI female (2021)', 'Life Expectancy at Birth, female (2021)', 'Expected Years of Schooling, female (2021)', 'Mean Years of Schooling, female (2021)', 'Gross National Income Per Capita, female (2021)', 'HDI male (2021)', 'Life Expectancy at Birth, male (2021)', 'Expected Years of Schooling, male (2021)', 'Mean Years of Schooling, male (2021)', 'Gross National Income Per Capita, male (2021)', 'Inequality-adjusted Human Development Index (2021)', 'Coefficient of human inequality (2021)', 'Overall loss (%) (2021)', 'Inequality in life expectancy (2021)', 'Inequality in eduation (2021)', 'Inequality in income (2021)', 'GII Rank (2021)', 'Gender Inequality Index (2021)', 'Maternal Mortality Ratio (deaths per 100,000 live births) (2021)', 'Adolescent Birth Rate (births per 1,000 women ages 15-19) (2021)', 'Labour force participation rate, female (% ages 15 and older) (2021)', 'Labour force participation rate, male (% ages 15 and older) (2021)', 'Difference from HDI rank (2021)', 'Planetary pressures-adjusted Human Development Index (2021)', 'Difference from HDI value (%) (2021)', 'Carbon dioxide emissions per capita (production) (tonnes) (2021)', 'Material footprint per capita (tonnes) (2021)']

In [3]:
# Required columns select cheddam
columns_needed = [
    'Country',
    'Human Development Index (2021)',
    'Life Expectancy at Birth (2021)',
    'Expected Years of Schooling (2021)',
    'Mean Years of Schooling (2021)',
    'Gross National Income Per Capita (2021)'
]

data = df[columns_needed].copy()

# Column names ni chinnaga easy ga rename cheddam
data.columns = ['Country', 'HDI', 'Life_Expectancy', 'Expected_Schooling', 'Mean_Schooling', 'GNI_per_capita']

print(data.shape)
data.head()

(195, 6)

,Country,HDI,Life_Expectancy,Expected_Schooling,Mean_Schooling,GNI_per_capita
0,Afghanistan,0.478,61.9824,10.263844,2.985070,1824.190915
1,Angola,0.586,61.6434,12.172100,5.417391,5465.617791
2,Albania,0.796,76.4626,14.448000,11.286455,14131.110390
3,Andorra,0.858,80.3684,13.300239,10.555120,51166.626610
4,United Arab Emirates,0.911,78.7104,15.717690,12.694030,62573.591810

In [4]:
data.isnull().sum()

Country               0
HDI                   4
Life_Expectancy       0
Expected_Schooling    2
Mean_Schooling        4
GNI_per_capita        2
dtype: int64

In [5]:
# Null unna rows ni tolagiddam
data = data.dropna()

print(data.shape)
data.isnull().sum()

(191, 6)

Country               0
HDI                   0
Life_Expectancy       0
Expected_Schooling    0
Mean_Schooling        0
GNI_per_capita        0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

# Independent variables (X) and dependent variable (y)
X = data[['Life_Expectancy', 'Expected_Schooling', 'Mean_Schooling', 'GNI_per_capita']]
y = data['HDI']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (152, 4)
Test size: (39, 4)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

R2 Score: 0.9808147179258669
Mean Squared Error: 0.0005089798068534027

In [8]:
import pickle
import os

# models folder already project structure lo undi
model_path = "../models/HDI.pkl"

with open(model_path, "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully at:", model_path)

Model saved successfully at: ../models/HDI.pkl